/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-14 09:46:25 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class myPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/KGITBANK%20FINAL%20PROJECT/cafe-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583405080786L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\t$(function(){\r\n");
      out.write("\t\t\t$(\"#final_submit\").click(function(){\r\n");
      out.write("\t\t\t\tlocation.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/myPageMain.do?memberId=");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\";\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#modifyBtn\").click(function(){\r\n");
      out.write("\t\t\t\talert(\"회원정보를 수정합니다.\");\r\n");
      out.write("\t\t\t\tvar formData = new FormData($(\"#myForm\")[0]);\r\n");
      out.write("\t\t\t\tconsole.log(formData);\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#modifyPwd\").click(function(){\r\n");
      out.write("\t\t\t\talert(\"비밀번호를 수정합니다.\");\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t\t$(\"#telNum\").keyup(function() {\r\n");
      out.write("\t\t\t    var regNumber = /^[0-9]*$/;\r\n");
      out.write("\t\t\t    console.log(\"번호 체크\");\r\n");
      out.write("\t\t\t    var temp = $(\"#telNum\").val();\r\n");
      out.write("\t\t\t    if(!regNumber.test(temp)){\r\n");
      out.write("\t\t\t\t\talert(\"숫자만 입력하세요\")\r\n");
      out.write("\t\t\t        $(\"#telNum\").val(temp.replace(/[^0-9]/g,\"\"));\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif($(\"#pwForm\").submit(function(){\r\n");
      out.write("\t\t\t\tif($(\"#memberPwd\").val() !== $(\"#pw2\").val()){\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호가 다릅니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#memberPwd\").val(\"\").focus();\r\n");
      out.write("\t\t\t\t\t$(\"#pw2\").val(\"\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if ($(\"#memberPwd\").val().length < 8) {\r\n");
      out.write("\t\t\t\t\talert(\"비밀번호는 8자 이상으로 설정해야 합니다.\");\r\n");
      out.write("\t\t\t\t\t$(\"#memberPwd\").val(\"\").focus();\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}else if($.trim($(\"#memberPwd\").val()) !== $(\"#memberPwd\").val()){\r\n");
      out.write("\t\t\t\t\talert(\"공백은 입력이 불가능합니다.\");\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\tif($(\"#wdForm\").submit(function(){\r\n");
      out.write("\t\t\t\tif(!confirm(\"탈퇴하시겠습니까?\")){\r\n");
      out.write("\t\t\t\t\treturn false;\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t}));\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t// 닉네임 중복확인 AJAX\r\n");
      out.write("\t\t\t$(\"#nickName\").keyup(function() {\r\n");
      out.write("\t\t\t\t$.ajax({\r\n");
      out.write("\t\t\t\t\turl : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/checkNickName.do\",\r\n");
      out.write("\t\t\t\t\ttype : \"POST\",\r\n");
      out.write("\t\t\t\t\tdata : {nickName : $(\"#nickName\").val()},\r\n");
      out.write("\t\t\t\t\tsuccess : function(result) {\r\n");
      out.write("\t\t\t\t\t\tif (result == 1) {\t//result가 1이면 중복되는 값이 존재함 \r\n");
      out.write("\t\t\t\t\t\t\t$(\"#check_nickName\").html(\"중복된 닉네임이 존재합니다.\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#modifyBtn\").attr('disabled',true);\r\n");
      out.write("\t\t\t\t\t\t} else {\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#check_nickName\").html(\"\");\r\n");
      out.write("\t\t\t\t\t\t\t$(\"#modifyBtn\").attr('disabled',false);\r\n");
      out.write("\t\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t});\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t});\r\n");
      out.write("\t\t\r\n");
      out.write("\t\tfunction readURL(input) {\r\n");
      out.write("\t\t\tif (input.files && input.files[0]) {\r\n");
      out.write("\t\t\t\tvar reader = new FileReader();\r\n");
      out.write("\t\t\t\treader.onload = function (e) {\r\n");
      out.write("\t\t\t\t\t$('#preview').attr('src', e.target.result);\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\treader.readAsDataURL(input.files[0]);\r\n");
      out.write("\t\t\t}\r\n");
      out.write("\t\t}  \r\n");
      out.write("\t</script>\r\n");
      out.write("\t<style>\r\n");
      out.write("\t\t@import url('https://fonts.googleapis.com/css2?family=Poor+Story&display=swap');\r\n");
      out.write("\t\t@import url('https://fonts.googleapis.com/css2?family=Gamja+Flower&display=swap');\r\n");
      out.write("\t\t.my_page_wrap{\r\n");
      out.write("\t\t\tfont-family: 'Poor Story', cursive !important;\r\n");
      out.write("\t\t\twidth:850px;\r\n");
      out.write("\t\t    margin: 30px auto !important;\r\n");
      out.write("\t\t    font-weight: bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.my_page_wrap h2{\r\n");
      out.write("\t\t\tfont-family: 'Gamja Flower', cursive;\r\n");
      out.write("\t\t\tfont-size: 30px;\r\n");
      out.write("\t\t\tfont-weight:bold;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.profile_image_div{\r\n");
      out.write("\t\t    margin-bottom: 20px;\r\n");
      out.write("\t    \tpadding: 0 0 0 10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.profile_image_div img{\r\n");
      out.write("\t\t\twidth:100px;\r\n");
      out.write("\t\t\theight:100px;\r\n");
      out.write("\t\t\tmargin-bottom:10px;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.profile_image_div label{\r\n");
      out.write("\t\t    margin-right: 20px;\r\n");
      out.write("\t    \tdisplay: block;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\t.profile_image_div input[type=file]{\r\n");
      out.write("\t\t    margin-left: 10px;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap label{\r\n");
      out.write("\t    \tfont-size: 20px;\r\n");
      out.write("\t\t    margin-top: 7px;\r\n");
      out.write("\t\t    color: #ef962d;\r\n");
      out.write("\t\t    font-weight:bold;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap input[type=text]{\r\n");
      out.write("\t    \tfont-size: 18px;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap input[type=submit], .my_page_wrap button[type=submit]{\r\n");
      out.write("\t\t    background: #ef962d !important;\r\n");
      out.write("\t\t    font-weight: 900;\r\n");
      out.write("\t\t    color: black !important;\r\n");
      out.write("\t\t    font-size: 18px;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap input[type=submit]:hover, .my_page_wrap button[type=submit]:hover{\r\n");
      out.write("\t    \tcolor: white !important;\r\n");
      out.write("\t    \ttransform:scale(1.1);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap input[type=submit]:last-child{\r\n");
      out.write("\t    \tmargin-top: 30px !important;\r\n");
      out.write("\t   \t    color: white !important;\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_wrap input[type=submit]:last-child:hover{\r\n");
      out.write("\t    \tcolor: black !important;\r\n");
      out.write("\t    \ttransform:scale(1.1);\r\n");
      out.write("\t    }\r\n");
      out.write("\t    .my_page_form_wrap{\r\n");
      out.write("\t    \tpadding-bottom: 30px;\r\n");
      out.write("\t    }\r\n");
      out.write("\t</style>\r\n");
      out.write("\t<div class=\"w3-content w3-container w3-margin-top my_page_wrap\">\r\n");
      out.write("\t\t<div class=\"w3-container w3-card-4\">\r\n");
      out.write("\t\t\t<div class=\"w3-center w3-large w3-margin-top\">\r\n");
      out.write("\t\t\t\t<h2>마이페이지</h2>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div class=\"my_page_form_wrap\">\r\n");
      out.write("\t\t\t\t<form id=\"myForm\" name=\"myForm\" class=\"my_form\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/updateMyPage.do\"  method=\"post\" enctype=\"multipart/form-data\">\r\n");
      out.write("\t\t\t\t\t<div class=\"profile_image_div\">\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t\t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>ID</label> \r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" type=\"text\" id=\"memberId\" name=\"memberId\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\"> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>Email</label> \r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" type=\"text\" id=\"email\" name=\"email\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.email }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" required> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("                  \t\t<label>닉네임</label> <input type=\"text\" class=\"w3-input\" id=\"nickName\" name=\"nickName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.nickName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" maxLength=\"8\" >\r\n");
      out.write("                  \t\t<span id=\"check_nickName\" class=\"w3-text-red\"></span>\r\n");
      out.write("              \t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>핸드폰번호</label> <input type=\"text\" class=\"w3-input\" id=\"telNum\" name=\"telNum\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.telNum }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>이름</label> <input type=\"text\" class=\"w3-input\" id=\"memberName\" name=\"memberName\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberName }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-center\">\r\n");
      out.write("\t\t\t\t\t\t<input type=\"submit\" id=\"modifyBtn\" value=\"회원정보 변경하기\" class=\"w3-button w3-block w3-black w3-ripple w3-margin-top w3-round\">\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t<form id=\"pwForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/updatePw.do\" method=\"post\">\t\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"memberId\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${ member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>현재 비밀번호</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" id=\"old_pw\" name=\"old_pw\" type=\"password\" placeholder=\"현재 비밀번호를 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>새로운 비밀번호</label> \r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" id=\"memberPwd\" name=\"memberPwd\" type=\"password\" placeholder=\"새로운 비밀번호를 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>새로운 비밀번호 확인</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" type=\"password\" id=\"pw2\" type=\"password\" placeholder=\"새로운 비밀번호를 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"modifyPwd\" class=\"w3-button w3-block w3-black w3-ripple w3-margin-top w3-round\">비밀번호 변경 하기</button>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<br>\r\n");
      out.write("\t\t\t\t<form id=\"wdForm\" action=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/member/withdrawal.do\" method=\"post\">\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"memberId\" readonly value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t<label>패스워드</label>\r\n");
      out.write("\t\t\t\t\t\t<input class=\"w3-input\" type=\"password\" name=\"memberPwd\"  placeholder=\"비밀번호를 입력하세요\" required>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"w3-center\">\r\n");
      out.write("\t\t\t\t\t\t<button type=\"submit\" id=\"byeBtn\" class=\"w3-button w3-block w3-black w3-ripple w3-margin-top w3-round\" >회원탈퇴</button> \r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t\t<div class=\"w3-center\">\r\n");
      out.write("\t\t\t\t\t<input type=\"submit\" value=\"닫기\" id=\"final_submit\" class=\"w3-button w3-block w3-black w3-ripple w3-margin-top w3-round\" >\r\n");
      out.write("\t\t\t\t</div>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/member/myPage.jsp(3,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/member/myPage.jsp(3,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/member/myPage.jsp(3,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/myPage.jsp(151,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.imageId.equals('basic')  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<label>프로필 사진</label>\r\n");
          out.write("\t\t\t\t\t\t    <input type= \"hidden\" name=\"originalImageId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.imageId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t\t    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/upload/photo_profile/profile_basic.png\" id=\"preview\"><br>\r\n");
          out.write("\t\t\t\t\t\t    <input type=\"file\"name=\"imageId\" id=\"i_imageId\"  onchange=\"readURL(this);\"   />\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/member/myPage.jsp(157,6) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${!member.imageId.equals('basic')  }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("\t\t\t\t\t\t\t<label>프로필 사진</label>\r\n");
          out.write("\t\t\t\t\t\t    <input type= \"hidden\"  name=\"originalImageId\" value=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.imageId }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" />\r\n");
          out.write("\t\t\t\t\t\t    <img src=\"");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("/resources/upload/photo_profile/");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.memberId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('/');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.imageId}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("\" id=\"preview\"><br>\r\n");
          out.write("\t\t\t\t\t\t    <input type=\"file\" name=\"imageId \" id=\"i_imageId\" onchange=\"readURL(this);\"   />\r\n");
          out.write("\t\t\t\t\t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
