/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.30
 * Generated at: 2020-05-14 09:26:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.common;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class layout_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/KGITBANK%20FINAL%20PROJECT/cafe-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafe/WEB-INF/lib/tiles-jsp-2.2.2.jar!/META-INF/tld/tiles-jsp.tld", Long.valueOf(1276606224000L));
    _jspx_dependants.put("/WEB-INF/lib/tiles-jsp-2.2.2.jar", Long.valueOf(1583480704681L));
    _jspx_dependants.put("jar:file:/C:/KGITBANK%20FINAL%20PROJECT/cafe-workspace/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cafe/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1583405080786L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fset_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>myCafe</title>\r\n");
      out.write("<!-- google charts -->\r\n");
      out.write("<script type=\"text/javascript\" src=\"https://www.gstatic.com/charts/loader.js\"></script>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.js\"></script>\r\n");
      out.write("<script src=\"https://use.fontawesome.com/releases/v5.2.0/js/all.js\"></script>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<style>\r\n");
      out.write("\t@import url('https://fonts.googleapis.com/css2?family=Pacifico&display=swap');\r\n");
      out.write("\t@import url('https://fonts.googleapis.com/css2?family=Nanum+Pen+Script&display=swap');\r\n");
      out.write("\t@import url('https://fonts.googleapis.com/css2?family=Poor+Story&display=swap');\r\n");
      out.write("\t@import url('https://fonts.googleapis.com/css2?family=Stylish&display=swap');\r\n");
      out.write("\t\r\n");
      out.write("\tli, ul, div, p, a {\r\n");
      out.write("\t\tmargin: 0;\r\n");
      out.write("\t\tpadding: 0;\r\n");
      out.write("\t\tlist-style-type: none;\r\n");
      out.write("\t\ttext-decoration:none;\r\n");
      out.write("\t\tcolor:black;\r\n");
      out.write("\t}\r\n");
      out.write("\tbutton, a, input[type=button], input[type=submit]{\r\n");
      out.write("\t\tcursor:pointer;\r\n");
      out.write("\t}\r\n");
      out.write("\t.banner_div {\r\n");
      out.write("\t\tbackground-image: url(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/image/main_banner1.jpg);\r\n");
      out.write("\t\tbackground-size: cover;\r\n");
      out.write("\t\tbackground-repeat: no-repeat;\r\n");
      out.write("\t\tbackground-position-y: -450px;\r\n");
      out.write("\t\theight: 400px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header_buttons_div{\r\n");
      out.write("\t\tline-height: 40px;\r\n");
      out.write("\t    font-size: 15px;\r\n");
      out.write("\t    text-align: right;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    font-family: 'Poor Story', cursive;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header_buttons_div input[type=button]{\r\n");
      out.write("\t    border: none;\r\n");
      out.write("\t    background: transparent;\r\n");
      out.write("\t    padding: 0;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: #ef962d;\r\n");
      out.write("\t   \tmargin: 0 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.header_buttons_div a{\r\n");
      out.write("\t\tcolor: #ef962d;\r\n");
      out.write("\t\tmargin: 0 10px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.top_section h1 {\r\n");
      out.write("\t\ttext-align: left;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    line-height: 40px;\r\n");
      out.write("\t    font-family: 'Pacifico', cursive !important;\r\n");
      out.write("\t    font-size: 45px;\r\n");
      out.write("\t    font-weight: 900;\r\n");
      out.write("\t    color: #ef962d;\r\n");
      out.write("\t    position: relative;\r\n");
      out.write("\t    top: 360px;\r\n");
      out.write("\t    left: 1057px;\r\n");
      out.write("\t    width: 144px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.top_section {\r\n");
      out.write("\t\twidth: 1200px;\r\n");
      out.write("\t\theight: 491px;\r\n");
      out.write("\t\tmargin: 0 auto;\r\n");
      out.write("\t\ttext-align: center;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu_div {\r\n");
      out.write("\t\theight: 50px;\r\n");
      out.write("\t\tline-height: 50px;\r\n");
      out.write("\t\tbackground-color: antiquewhite;\r\n");
      out.write("\t\tborder: 1px solid #ef962d;\r\n");
      out.write("\t\tfont-family: 'Nanum Pen Script', cursive;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu_li {\r\n");
      out.write("\t\tfloat: left;\r\n");
      out.write("\t\tmargin: 0 20px;\r\n");
      out.write("\t\tfont-weight: bold;\r\n");
      out.write("\t\tfont-size:30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.menu_li a{\r\n");
      out.write("\t\tcolor: coral;\r\n");
      out.write("\t}\r\n");
      out.write("\t.main_div{\r\n");
      out.write("\t    width: 1200px;\r\n");
      out.write("\t    margin: 0 auto;\r\n");
      out.write("\t    min-height: 1200px;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t}\r\n");
      out.write("\taside{\r\n");
      out.write("\t    width: 250px;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    display: inline-block !important;\r\n");
      out.write("\t    left: 160px;\r\n");
      out.write("\t    margin-top: 30px;\r\n");
      out.write("\t    font-size: 13px;\r\n");
      out.write("\t}\r\n");
      out.write("\taside+div{\r\n");
      out.write("\t\twidth: 950px;\r\n");
      out.write("\t    margin: 0;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t    float: right;\r\n");
      out.write("\t}\r\n");
      out.write("\t.cafe_info_wrap{\r\n");
      out.write("\t\tborder: 1px solid #ef962d;\r\n");
      out.write("        height: 335px;\r\n");
      out.write("\t    font-family: 'Stylish', sans-serif;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mem_info_wrap{\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    width: 220px;\r\n");
      out.write("\t    margin: 0px auto 15px;\r\n");
      out.write("\t    padding-top: 25px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mem_info_wrap img{\r\n");
      out.write("\t    width: 60px;\r\n");
      out.write("\t    height: 60px;\r\n");
      out.write("\t    border: 1px solid #ef962d;\r\n");
      out.write("\t    border-radius: 32px;\r\n");
      out.write("\t    vertical-align: top;\r\n");
      out.write("\t    margin-left: -15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mem_info_wrap span{\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.mem_stat_wrap{\r\n");
      out.write("\t    text-align: left;\r\n");
      out.write("\t    margin-top: 25px;\r\n");
      out.write("\t    width: 200px;\r\n");
      out.write("\t    margin: 25px auto 0;\r\n");
      out.write("\t}\r\n");
      out.write("\t.guest_buttons_wrap{\r\n");
      out.write("\t    margin-top: 80px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.guest_buttons_wrap a{\r\n");
      out.write("\t    padding: 10px 20px;\r\n");
      out.write("    \tborder: 1px solid #ef962d;\r\n");
      out.write("    \tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\t.info_button{\r\n");
      out.write("\t    border: 1px solid #ef962d;\r\n");
      out.write("\t    background: #ef962d;\r\n");
      out.write("\t    padding: 2px 50px;\r\n");
      out.write("\t    width: 200px;\r\n");
      out.write("\t    margin: 5px;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    font-size: 20px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.side_search_form input{\r\n");
      out.write("\t\tfont-family: 'Poor Story', cursive;\r\n");
      out.write("\t}\r\n");
      out.write("\t.side_search_form input[type=text]{\r\n");
      out.write("\t    padding: 0 5px;\r\n");
      out.write("\t    line-height: 30px; \r\n");
      out.write("\t    width: 205px;\r\n");
      out.write("        border: 2px solid #ef962d;\r\n");
      out.write("\t}\r\n");
      out.write("\t.side_search_form input[type=submit]{\r\n");
      out.write("\t\theight: 34px;\r\n");
      out.write("\t    border: 1px solid #ef962d;\r\n");
      out.write("\t    background: #ef962d;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    width: 40px;\r\n");
      out.write("\t    padding-bottom:2px;\r\n");
      out.write("\t    margin-left: -5px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_outer_ul{\r\n");
      out.write("\t\tmargin:15px 0 30px;\r\n");
      out.write("\t   \tfont-family: 'Stylish', sans-serif;\r\n");
      out.write("\t   \tfont-size:15px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_outer_li{\r\n");
      out.write("\t    line-height: 40px;\r\n");
      out.write("\t    border-top: 3px solid #ef962d;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_outer_li > span{\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: #ef962d;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    display: inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_inner_ul {\r\n");
      out.write("\t\tborder-top: 1px solid #ef962d;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_inner_li{\r\n");
      out.write("\t    border-bottom: 1px solid #ef962d2e;\r\n");
      out.write("\t}\r\n");
      out.write("\t.ctg_menu_inner_li:hover{\r\n");
      out.write("\t\tbackground:antiquewhite;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap{\r\n");
      out.write("\t    margin-top: 200px;\r\n");
      out.write("\t\tmargin-bottom: 30px;\r\n");
      out.write("\t\tfont-family: 'Poor Story', cursive !important;\r\n");
      out.write("\t\ttext-align: right;\r\n");
      out.write("\t\tborder: 1px dotted #ef962d;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap > p{\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    line-height: 30px;\r\n");
      out.write("\t    font-size: 16px;\r\n");
      out.write("\t    font-weight: bold;\r\n");
      out.write("\t    color: coral;\r\n");
      out.write("\t    background: antiquewhite;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap ul.recent_article_ul{\r\n");
      out.write("\t \ttext-align: left;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap li.recent_article_li{\r\n");
      out.write("\t    height: 30px;\r\n");
      out.write("    \tpadding: 5px;\r\n");
      out.write("    \tline-height: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap .recent_article_li a{\r\n");
      out.write("\t\twidth: 245px;\r\n");
      out.write("   \t\tdisplay: inline-block;\r\n");
      out.write("\t    text-overflow: ellipsis;\r\n");
      out.write("\t    overflow: hidden;\r\n");
      out.write("\t    line-height: 30px;\r\n");
      out.write("\t}\r\n");
      out.write("\t.recent_article_wrap button{\r\n");
      out.write("    \tbackground: #ef962d;\r\n");
      out.write("    \tborder: 1px solid #ef962d;\r\n");
      out.write("    \tfont-weight: bold;\r\n");
      out.write("\t}\r\n");
      out.write("\tfooter{\r\n");
      out.write("\t\tfont-family: 'Poor Story', cursive !important;\r\n");
      out.write("\t    text-align: center;\r\n");
      out.write("\t    font-size:12px;\r\n");
      out.write("\t    margin-top: 40px;\r\n");
      out.write("\t    width: 100%;\r\n");
      out.write("\t    border-top: 1px solid #ef962d;\r\n");
      out.write("\t    padding: 30px 0;\r\n");
      out.write("\t  }\r\n");
      out.write("\tp.contact{\r\n");
      out.write("  \t    color: #ef962d;\r\n");
      out.write("    \tfont-weight: bold;\r\n");
      out.write("    \tfont-size: 13px\r\n");
      out.write("\t}\r\n");
      out.write("\taddress > a{\r\n");
      out.write("\t  \ttext-decoration: none;\r\n");
      out.write("\t  \tcolor:#999;\r\n");
      out.write("\t  \tfont-style: normal;\r\n");
      out.write("\t  \tdisplay:inline-block;\r\n");
      out.write("\t}\r\n");
      out.write("\tp.copyright{\r\n");
      out.write("\t  \tcolor:#000;\r\n");
      out.write("\t  \tfont-weight: bold;\r\n");
      out.write("  \t    margin-top: 10px;\r\n");
      out.write("\t}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<header class=\"top_section\">\r\n");
      out.write("\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</header>\r\n");
      out.write("\t<div class=\"main_div\">\r\n");
      out.write("\t\t<aside>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</aside>\r\n");
      out.write("\t\t<div>\r\n");
      out.write("\t\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\t<footer>\r\n");
      out.write("\t\t");
      if (_jspx_meth_tiles_005finsertAttribute_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\t</footer>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fset_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:set
    org.apache.taglibs.standard.tag.rt.core.SetTag _jspx_th_c_005fset_005f0 = (org.apache.taglibs.standard.tag.rt.core.SetTag) _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.SetTag.class);
    boolean _jspx_th_c_005fset_005f0_reused = false;
    try {
      _jspx_th_c_005fset_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fset_005f0.setParent(null);
      // /WEB-INF/views/common/layout.jsp(5,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setVar("contextPath");
      // /WEB-INF/views/common/layout.jsp(5,0) name = value type = javax.el.ValueExpression reqTime = true required = false fragment = false deferredValue = true expectedTypeName = java.lang.Object deferredMethod = false methodSignature = null
      _jspx_th_c_005fset_005f0.setValue(new org.apache.jasper.el.JspValueExpression("/WEB-INF/views/common/layout.jsp(5,0) '${pageContext.request.contextPath}'",_jsp_getExpressionFactory().createValueExpression(_jspx_page_context.getELContext(),"${pageContext.request.contextPath}",java.lang.Object.class)).getValue(_jspx_page_context.getELContext()));
      int _jspx_eval_c_005fset_005f0 = _jspx_th_c_005fset_005f0.doStartTag();
      if (_jspx_th_c_005fset_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fset_0026_005fvar_005fvalue_005fnobody.reuse(_jspx_th_c_005fset_005f0);
      _jspx_th_c_005fset_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fset_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fset_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f0 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    try {
      _jspx_th_tiles_005finsertAttribute_005f0.setJspContext(_jspx_page_context);
      // /WEB-INF/views/common/layout.jsp(265,2) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f0.setName("header");
      _jspx_th_tiles_005finsertAttribute_005f0.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f1 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    try {
      _jspx_th_tiles_005finsertAttribute_005f1.setJspContext(_jspx_page_context);
      // /WEB-INF/views/common/layout.jsp(269,3) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f1.setName("side");
      _jspx_th_tiles_005finsertAttribute_005f1.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f2 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    try {
      _jspx_th_tiles_005finsertAttribute_005f2.setJspContext(_jspx_page_context);
      // /WEB-INF/views/common/layout.jsp(272,3) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f2.setName("body");
      _jspx_th_tiles_005finsertAttribute_005f2.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_tiles_005finsertAttribute_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tiles:insertAttribute
    org.apache.tiles.jsp.taglib.InsertAttributeTag _jspx_th_tiles_005finsertAttribute_005f3 = new org.apache.tiles.jsp.taglib.InsertAttributeTag();
    _jsp_getInstanceManager().newInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    try {
      _jspx_th_tiles_005finsertAttribute_005f3.setJspContext(_jspx_page_context);
      // /WEB-INF/views/common/layout.jsp(276,2) name = name type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tiles_005finsertAttribute_005f3.setName("footer");
      _jspx_th_tiles_005finsertAttribute_005f3.doTag();
    } finally {
      _jsp_getInstanceManager().destroyInstance(_jspx_th_tiles_005finsertAttribute_005f3);
    }
    return false;
  }
}
